// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMtsZHe0g7Oi0NvGWlbHFni53KZGDMrMU',
    appId: '1:1027919421405:web:0098c9f04dc0b553b06034',
    messagingSenderId: '1027919421405',
    projectId: 'dabill-notifications',
    authDomain: 'dabill-notifications.firebaseapp.com',
    storageBucket: 'dabill-notifications.appspot.com',
    measurementId: 'G-1CQ0WDW2TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVY8FyfQ1yyS_AZxrXUAtyB3SJ1wKpRFQ',
    appId: '1:1027919421405:android:44d958dab5aad61db06034',
    messagingSenderId: '1027919421405',
    projectId: 'dabill-notifications',
    storageBucket: 'dabill-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcyK7w-E76M3ISQW42n3sgCTZCTQlFTfg',
    appId: '1:1027919421405:ios:e35ce5f36e707648b06034',
    messagingSenderId: '1027919421405',
    projectId: 'dabill-notifications',
    storageBucket: 'dabill-notifications.appspot.com',
    iosClientId: '1027919421405-97fp809ekcm95ftk3nhgerp4br0jj22t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcyK7w-E76M3ISQW42n3sgCTZCTQlFTfg',
    appId: '1:1027919421405:ios:e35ce5f36e707648b06034',
    messagingSenderId: '1027919421405',
    projectId: 'dabill-notifications',
    storageBucket: 'dabill-notifications.appspot.com',
    iosClientId: '1027919421405-97fp809ekcm95ftk3nhgerp4br0jj22t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
